# Generated by Django 5.1.5 on 2025-02-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_barberinfo_image_alter_servicesdes_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barberinfo',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='servicesdes',
            options={'ordering': ['-created_on']},
        ),
    ]
