# Generated by Django 5.1.5 on 2025-02-03 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_barber_alter_bookcover_options_barberservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.barber')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.barberservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
