# Generated by Django 5.1.5 on 2025-02-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-updated_on']},
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
