# Generated by Django 5.1.5 on 2025-02-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_booking_options_booking_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='barber_name',
            field=models.CharField(max_length=50),
        ),
    ]
