# Generated by Django 5.1.5 on 2025-02-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_barber_barber_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberservice',
            name='service_name',
            field=models.CharField(max_length=50),
        ),
    ]
