# Generated by Django 5.1.5 on 2025-12-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_remove_booking_unique_booking_combination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcover',
            name='booking_intro',
            field=models.TextField(max_length=300),
        ),
    ]
