# Generated by Django 5.1.5 on 2025-02-09 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
        ('book', '0007_booking_date_booking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created_on'], 'verbose_name': 'About Me', 'verbose_name_plural': 'About Me'},
        ),
        migrations.AddField(
            model_name='about',
            name='about_barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='book.barber'),
        ),
    ]
