# Generated by Django 5.1.5 on 2025-02-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_about_about_barber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber_name', models.CharField(max_length=50)),
                ('barber_shop', models.CharField(max_length=50, unique=True)),
                ('business_type', models.CharField(choices=[('barber', 'Barber'), ('hair_stylist', 'Hair Stylist'), ('beauty_salon', 'Beauty Salon')], max_length=50)),
                ('service_offered', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('more_info', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_on'],
                'constraints': [models.UniqueConstraint(fields=('barber_name', 'barber_shop'), name='unique_barber_and_shop')],
            },
        ),
    ]
