# Generated by Django 5.1.5 on 2025-02-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_collaboration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='updated_on',
        ),
    ]
