# Generated by Django 5.1.5 on 2025-02-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_collaboration_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='owner',
        ),
    ]
