# Generated by Django 5.1.5 on 2025-02-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['created_on'], 'verbose_name': 'User Message', 'verbose_name_plural': 'User Messages'},
        ),
        migrations.RemoveConstraint(
            model_name='contactus',
            name='unique_email_and_message',
        ),
    ]
