# Generated by Django 5.1.5 on 2025-02-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='is_finished',
        ),
    ]
