# Generated by Django 5.1.5 on 2025-02-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_remove_contactus_is_finished'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
